// default package
// Generated 27/04/2020 10:00:04 PM by Hibernate Tools 5.4.14.Final

/**
 * Mensaje generated by hbm2java
 */
public class Mensaje implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String email;
	private String website;
	private String mensaje;

	public Mensaje() {
	}

	public Mensaje(String nombre, String email, String website, String mensaje) {
		this.nombre = nombre;
		this.email = email;
		this.website = website;
		this.mensaje = mensaje;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

}
